language: node_js

node_js:
  - "lts/*"

services:
  - docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - make build-image image-publish IMAGE_VERSION=$TRAVIS_BRANCH

branches:
  only:
    - develop
    - tags
    - feature/build-docker-image-on-travis-ci
